import './globals.css'
import { Karla } from 'next/font/google'
import { Montserrat } from 'next/font/google'



const borel = Montserrat({
  weight: '400',
  subsets: ['latin'],
})

export const metadata = {
  title: 'ELESTIA',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={borel.className}>{children}</body>
    </html>
  )
}
